// Shared canonical display labels; this module has no runtime dependencies.
export const KNOWN_CANONICAL_IDENTIFIERS_VI: Record<string, string> = {
  // Palaces
  "ziwei.palace.life": "cung Mệnh",
  "ziwei.palace.siblings": "cung Huynh Đệ",
  "ziwei.palace.spouse": "cung Phu Thê",
  "ziwei.palace.children": "cung Tử Tức",
  "ziwei.palace.wealth": "cung Tài Bạch",
  "ziwei.palace.health": "cung Tật Ách",
  "ziwei.palace.travel": "cung Thiên Di",
  "ziwei.palace.friends": "cung Nô Bộc",
  "ziwei.palace.career": "cung Quan Lộc",
  "ziwei.palace.property": "cung Điền Trạch",
  "ziwei.palace.fortune": "cung Phúc Đức",
  "ziwei.palace.parents": "cung Phụ Mẫu",

  // Major Stars
  "ziwei.star.ziwei": "sao Tử Vi",
  "ziwei.star.purple-emperor": "sao Tử Vi",
  "ziwei.star.tianji": "sao Thiên Cơ",
  "ziwei.star.taiyang": "sao Thái Dương",
  "ziwei.star.wuqu": "sao Vũ Khúc",
  "ziwei.star.tiantong": "sao Thiên Đồng",
  "ziwei.star.lianzhen": "sao Liêm Trinh",
  "ziwei.star.tianfu": "sao Thiên Phủ",
  "ziwei.star.taiyin": "sao Thái Âm",
  "ziwei.star.tanlang": "sao Tham Lang",
  "ziwei.star.jumen": "sao Cự Môn",
  "ziwei.star.tianxiang": "sao Thiên Tướng",
  "ziwei.star.tianliang": "sao Thiên Lương",
  "ziwei.star.qisha": "sao Thất Sát",
  "ziwei.star.pojun": "sao Phá Quân",

  // Minor Stars & Adjectives
  "ziwei.star.zuofu": "sao Tả Phù",
  "ziwei.star.youbi": "sao Hữu Bật",
  "ziwei.star.wenchang": "sao Văn Xương",
  "ziwei.star.wenqu": "sao Văn Khúc",
  "ziwei.star.lucun": "sao Lộc Tồn",
  "ziwei.star.tianma": "sao Thiên Mã",
  "ziwei.star.qingyang": "sao Kình Dương",
  "ziwei.star.tuoluo": "sao Đà La",
  "ziwei.star.huoxing": "sao Hỏa Tinh",
  "ziwei.star.lingxing": "sao Linh Tinh",
  "ziwei.star.tiankui": "sao Thiên Khôi",
  "ziwei.star.tianyue": "sao Thiên Việt",
  "ziwei.star.dikong": "sao Địa Không",
  "ziwei.star.dijie": "sao Địa Kiếp",
  "ziwei.star.hongluan": "sao Hồng Loan",
  "ziwei.star.tianxi": "sao Thiên Hỷ",
  "ziwei.star.tianyao": "sao Thiên Diêu",
  "ziwei.star.xianchi": "sao Hàm Trì",
  "ziwei.star.jieshen": "sao Giải Thần",
  "ziwei.star.santai": "sao Tam Thai",
  "ziwei.star.bazuo": "sao Bát Tọa",
  "ziwei.star.enguang": "sao Ân Quang",
  "ziwei.star.tiangui": "sao Thiên Quý",
  "ziwei.star.longchi": "sao Long Trì",
  "ziwei.star.fengge": "sao Phượng Các",
  "ziwei.star.tiancai": "sao Thiên Tài",
  "ziwei.star.tianshou": "sao Thiên Thọ",
  "ziwei.star.taifu": "sao Thai Phụ",
  "ziwei.star.fenggao": "sao Phong Cáo",
  "ziwei.star.tianwu": "sao Thiên Vu",
  "ziwei.star.huagai": "sao Hoa Cái",
  "ziwei.star.tianguan": "sao Thiên Quan",
  "ziwei.star.tianfu-adj": "sao Thiên Phúc",
  "ziwei.star.tianchu": "sao Thiên Trù",
  "ziwei.star.tianyue-adj": "sao Thiên Nguyệt",
  "ziwei.star.tiande": "sao Thiên Đức",
  "ziwei.star.yuede": "sao Nguyệt Đức",
  "ziwei.star.tiankong": "sao Thiên Không",
  "ziwei.star.xunkong": "sao Tuần Không",
  "ziwei.star.jielu": "sao Triệt Lộ",
  "ziwei.star.kongwang": "sao Không Vong",
  "ziwei.star.longde": "sao Long Đức",
  "ziwei.star.jiekong": "sao Tiệt Không",
  "ziwei.star.jiesha": "sao Kiếp Sát",
  "ziwei.star.dahao": "sao Đại Hao",
  "ziwei.star.guchen": "sao Cô Thần",
  "ziwei.star.guasu": "sao Quả Tú",
  "ziwei.star.feilian": "sao Phi Liêm",
  "ziwei.star.posui": "sao Phá Toái",
  "ziwei.star.tianxing": "sao Thiên Hình",
  "ziwei.star.yinsha": "sao Âm Sát",
  "ziwei.star.tianku": "sao Thiên Khốc",
  "ziwei.star.tianxu": "sao Thiên Hư",
  "ziwei.star.tianshi": "sao Thiên Sứ",
  "ziwei.star.tianshang": "sao Thiên Thương",
  "ziwei.star.nianjie": "sao Niên Giải",
  "ziwei.star.boshi": "sao Bác Sĩ",
  "ziwei.star.lishi": "sao Lực Sĩ",
  "ziwei.star.qinglong": "sao Thanh Long",
  "ziwei.star.xiaohao": "sao Tiểu Hao",
  "ziwei.star.jiangjun": "sao Tướng Quân",
  "ziwei.star.zhoushu": "sao Tấu Thư",
  "ziwei.star.feilian-dec": "sao Phi Liêm",
  "ziwei.star.xishen": "sao Hỷ Thần",
  "ziwei.star.bingfu": "sao Bệnh Phù",
  "ziwei.star.dahao-dec": "sao Đại Hao",
  "ziwei.star.fubing": "sao Phục Binh",
  "ziwei.star.guanfu": "sao Quan Phủ",
  "ziwei.star.jiangxing": "sao Tướng Tinh",
  "ziwei.star.panan": "sao Phan An",
  "ziwei.star.suiyi": "sao Tuế Dịch",
  "ziwei.star.xiishen": "sao Tức Thần",
  "ziwei.star.huagai-dec": "sao Hoa Cái",
  "ziwei.star.jiesha-dec": "sao Kiếp Sát",
  "ziwei.star.zhaisha": "sao Tai Sát",
  "ziwei.star.tiansha": "sao Thiên Sát",
  "ziwei.star.zhibei": "sao Chỉ Bối",
  "ziwei.star.xianchi-dec": "sao Hàm Trì",
  "ziwei.star.yuesha": "sao Nguyệt Sát",
  "ziwei.star.wangshen": "sao Vong Thần",
  "ziwei.star.suijian": "sao Thái Tuế",
  "ziwei.star.huiqi": "sao Hối Khí",
  "ziwei.star.sangmen": "sao Tang Môn",
  "ziwei.star.guansuo": "sao Quán Sách",
  "ziwei.star.gwanfu": "sao Quan Phù",
  "ziwei.star.xiaohao-sq": "sao Tiểu Hao",
  "ziwei.star.longde-dec": "sao Long Đức",
  "ziwei.star.baihu": "sao Bạch Hổ",
  "ziwei.star.tiande-dec": "sao Thiên Đức",
  "ziwei.star.diaoke": "sao Điếu Khách",
  "ziwei.star.bingfu-sq": "sao Bệnh Phù",

  // Transformations
  "ziwei.transformation.prosperity": "Hóa Lộc",
  "ziwei.transformation.power": "Hóa Quyền",
  "ziwei.transformation.fame": "Hóa Khoa",
  "ziwei.transformation.obstacle": "Hóa Kỵ",
  "ziwei.trans.hua_lu": "Hóa Lộc",
  "ziwei.trans.hua_quyen": "Hóa Quyền",
  "ziwei.trans.hua_khoa": "Hóa Khoa",
  "ziwei.trans.hua_ky": "Hóa Kỵ",
  "ziwei.brightness.bright": "Sáng",
  "ziwei.relation.opposite": "xung chiếu",

  // Brightness
  "ziwei.brightness.exalted": "Miếu",
  "ziwei.brightness.prosperous": "Vượng",
  "ziwei.brightness.favorable": "Đắc",
  "ziwei.brightness.neutral": "Bình",
  "ziwei.brightness.unfavorable": "Hãm",
  "ziwei.brightness.weak": "Nhược",

  // Relations
  "ziwei.relation.triad": "tam hợp",
  "ziwei.relation.opposition": "xung chiếu",
  "ziwei.relation.flanking": "giáp cung",

  // Branches
  "ziwei.branch.rat": "Tý",
  "ziwei.branch.ox": "Sửu",
  "ziwei.branch.tiger": "Dần",
  "ziwei.branch.rabbit": "Mão",
  "ziwei.branch.dragon": "Thìn",
  "ziwei.branch.snake": "Tỵ",
  "ziwei.branch.horse": "Ngọ",
  "ziwei.branch.goat": "Mùi",
  "ziwei.branch.monkey": "Thân",
  "ziwei.branch.rooster": "Dậu",
  "ziwei.branch.dog": "Tuất",
  "ziwei.branch.pig": "Hợi",

  // Stems
  "ziwei.stem.jia": "Giáp",
  "ziwei.stem.yi": "Ất",
  "ziwei.stem.bing": "Bính",
  "ziwei.stem.ding": "Đinh",
  "ziwei.stem.wu": "Mậu",
  "ziwei.stem.ji": "Kỷ",
  "ziwei.stem.geng": "Canh",
  "ziwei.stem.xin": "Tân",
  "ziwei.stem.ren": "Nhâm",
  "ziwei.stem.gui": "Quý",

  // Cycles
  "ziwei.cycle.born": "Trường Sinh",
  "ziwei.cycle.infancy": "Mộc Dục",
  "ziwei.cycle.adolescence": "Quan Đới",
  "ziwei.cycle.adulthood": "Lâm Quan",
  "ziwei.cycle.prime": "Đế Vượng",
  "ziwei.cycle.weak": "Suy",
  "ziwei.cycle.sick": "Bệnh",
  "ziwei.cycle.dead": "Tử",
  "ziwei.cycle.buried": "Mộ",
  "ziwei.cycle.dissipated": "Tuyệt",
  "ziwei.cycle.embryo": "Thai",
  "ziwei.cycle.molding": "Dưỡng",
};
