import { FreeStructuralOverviewDocV1Schema, FreeStructuralPalaceDocV1Schema, ziweiMajorStarMeaning, ZIWEI_MAJOR_STAR_MEANING_VERSION, type FreeStructuralOverviewDocV1, type FreeStructuralPalaceDocV1, type NormalizedZiweiChartV1, } from "@lasoviet/contracts";
import { computeNormalizedPalaceScores, getPalaceRelations } from "../reports/structural-palace-score.js";
import { freePalaceLabel } from "./free-palace-labels.js";
type Locale = "vi" | "en";
type Palace = NormalizedZiweiChartV1["palaces"][number];
export const FREE_OVERVIEW_RENDERER_VERSION = `structural-overview-v1:${ZIWEI_MAJOR_STAR_MEANING_VERSION}:fd111`;
const label = (locale: Locale, id: string) => freePalaceLabel(locale, id)?.replace(/^sao\s+/u, "") ?? (locale === "vi" ? "yếu tố chưa có tên được đối chiếu" : "an element without a verified display name");
const domains: Record<string, {
    vi: string;
    en: string;
    viDo: string;
    enDo: string;
    viAvoid: string;
    enAvoid: string;
}> = {
    life: { vi: "Mệnh là điểm bắt đầu để nhìn cách bạn tiếp nhận tình huống và tự quyết định.", en: "The Life Palace provides a starting point for reflecting on how you approach situations and make choices, rather than a complete personality assessment.", viDo: "Ghi lại một quyết định gần đây và điều khiến bạn chọn cách đó.", enDo: "Write down a recent decision, the reason behind it, and whether the outcome supports your initial assumption.", viAvoid: "Tránh dùng một đặc điểm để gắn nhãn toàn bộ con người mình.", enAvoid: "Avoid treating one characteristic as a permanent label for every aspect of your identity or every choice you make." },
    career: { vi: "Quan Lộc gợi góc nhìn về cách làm việc, vai trò và trách nhiệm.", en: "The Career Palace offers a perspective on work, responsibility, and the roles you choose. It does not specify an occupation, employer, promotion date, or guaranteed professional outcome.", viDo: "Chọn một việc quan trọng, xác định người chịu trách nhiệm và tiêu chí hoàn thành.", enDo: "Choose one important task, agree who is responsible for it, and define a clear completion criterion before starting the work.", viAvoid: "Tránh đổi nghề chỉ vì một điểm số trên lá số.", enAvoid: "Avoid changing careers solely because of a chart score; compare the reading with your skills, commitments, and actual work experience." },
    wealth: { vi: "Tài Bạch đặt câu hỏi về cách sử dụng và giữ nguồn lực.", en: "The Wealth Palace invites reflection on how you use, protect, and allocate resources. Its structural score cannot estimate your income, assets, debt, or the return on an investment.", viDo: "Soát khoản thu chi thực tế và dành một phần dự phòng trước khi quyết định lớn.", enDo: "Review actual income and expenses, establish a reserve, and write down the cost and tradeoffs before making a significant commitment.", viAvoid: "Tránh coi luận giải là tín hiệu mua bán hoặc cam kết lợi nhuận.", enAvoid: "Avoid interpreting this reading as a trading signal, a promise of profit, or evidence that a financial risk is affordable." },
    spouse: { vi: "Phu Thê giúp suy ngẫm về kỳ vọng và cách phối hợp trong quan hệ gần gũi.", en: "The Partnership Palace provides a lens for reflecting on expectations, communication, and cooperation in close relationships. It cannot establish another person's feelings or predict a particular relationship outcome.", viDo: "Nói rõ một nhu cầu và lắng nghe câu trả lời thay vì tự đoán ý người kia.", enDo: "Express one concrete need, ask for the other person's perspective, and agree on a practical step that both people can assess.", viAvoid: "Tránh kết luận hợp hay không hợp từ riêng cung này.", enAvoid: "Avoid deciding that a relationship is compatible or incompatible from this palace alone; consider consent, trust, behaviour, and shared circumstances." },
    travel: { vi: "Thiên Di gợi cách bạn bước vào môi trường bên ngoài và tiếp xúc người mới.", en: "The Travel Palace concerns your encounter with the outside environment, including unfamiliar settings and people. It is a reflective lens on context, not a description of how everyone actually sees you.", viDo: "Thử một thay đổi nhỏ trong cách giới thiệu bản thân rồi quan sát phản hồi thật.", enDo: "Try a small change in how you introduce yourself, then observe real responses across several situations before drawing a conclusion.", viAvoid: "Tránh cho rằng mọi người đều nhìn mình theo cùng một cách.", enAvoid: "Avoid assuming that everyone perceives you in the same way, or that a structural reading can replace direct feedback from others." },
    fortune: { vi: "Phúc Đức gợi cách nhìn nguồn nâng đỡ tinh thần và nhịp sống bền vững.", en: "The Fortune Palace offers a perspective on sources of emotional support and the routines that help you sustain daily life. It does not measure happiness, personal worth, or a predetermined amount of good fortune.", viDo: "Giữ một thói quen nghỉ ngơi có thể thực hiện đều và nhận diện người hỗ trợ đáng tin.", enDo: "Choose a manageable routine for rest and identify a trusted source of support, then observe whether that routine helps over time.", viAvoid: "Tránh dùng điểm cấu trúc để tự đánh giá giá trị bản thân.", enAvoid: "Avoid using a structural score to judge your worth, to compare happiness with other people, or to dismiss a real need for support." },
    parents: { vi: "Phụ Mẫu mở góc nhìn về quan hệ với cha mẹ và người hướng dẫn.", en: "The Parents Palace offers a lens on your relationship with parents and guiding figures. It cannot establish someone's intentions, family history, or whether a particular person will provide support.", viDo: "Phân biệt điều được kỳ vọng với điều hai bên đã thật sự trao đổi và thống nhất.", enDo: "Separate what you expect from what has actually been discussed, then ask a clear question about one responsibility or boundary.", viAvoid: "Tránh suy đoán ý định của người thân từ tên sao.", enAvoid: "Avoid inferring a family member's intentions from a star name; use direct communication and observable behaviour to understand the relationship." },
};
for (const [key, vi, en, viDo, enDo, viAvoid, enAvoid] of [
    ["siblings", "Huynh Đệ gợi góc nhìn về cách chia sẻ và phối hợp với anh chị em.", "The Siblings Palace offers a perspective on sharing and cooperation with siblings.", "Trao đổi rõ việc chung và phần trách nhiệm của mỗi người.", "Discuss a shared task and each person's responsibility explicitly.", "Tránh suy đoán tình cảm của anh chị em từ một điểm số.", "Avoid inferring a sibling's feelings from a structural score."],
    ["children", "Tử Tức gợi góc nhìn về chăm sóc, hướng dẫn và sự tiếp nối.", "The Children Palace offers a perspective on care, guidance, and continuity.", "Quan sát nhu cầu thực tế của người được chăm sóc trước khi đặt kỳ vọng.", "Observe the actual needs of someone in your care before setting expectations.", "Tránh dùng cung này để dự đoán khả năng sinh sản hay số con.", "Avoid using this palace to predict fertility or the number of children."],
    ["health", "Tật Ách gợi câu hỏi về cách chăm sóc bản thân và duy trì nhịp sống.", "The Health Palace invites reflection on self-care and sustainable routines.", "Theo dõi nhịp sinh hoạt thực tế và hỏi chuyên gia khi có triệu chứng.", "Observe your actual routines and consult a qualified professional about symptoms.", "Tránh dùng lá số để chẩn đoán bệnh hoặc thay đổi điều trị.", "Avoid using a chart to diagnose illness or change medical treatment."],
    ["friends", "Nô Bộc gợi góc nhìn về cộng tác và mạng lưới hỗ trợ.", "The Friends Palace offers a perspective on collaboration and support networks.", "Thống nhất kỳ vọng và cách phản hồi khi cùng làm một việc.", "Agree on expectations and feedback before working on a shared task.", "Tránh kết luận ai đáng tin chỉ từ vị trí sao.", "Avoid deciding whom to trust solely from star placements."],
    ["property", "Điền Trạch gợi góc nhìn về nơi ở và những nền tảng vật chất được duy trì.", "The Property Palace offers a perspective on home and material foundations.", "Đánh giá nhu cầu nơi ở cùng khả năng tài chính thực tế.", "Assess housing needs alongside your actual financial capacity.", "Tránh xem điểm cung là dự báo mua nhà hay giá bất động sản.", "Avoid treating the palace score as a prediction of property ownership or prices."],
] as const)
    domains[key] = { vi, en, viDo, enDo, viAvoid, enAvoid };
// Reflective practices derived from the versioned product meanings above; not new divinatory rules.
const practices: Record<string, {
    viDo: string;
    enDo: string;
    viAvoid: string;
    enAvoid: string;
}> = {
    ziwei: { viDo: "Nhận trách nhiệm rõ ràng cho một quyết định và kiểm tra kết quả mình đã cam kết.", enDo: "Take clear responsibility for one decision and check whether you delivered the outcome you committed to.", viAvoid: "Tránh tự gánh mọi việc chỉ vì muốn giữ quyền chủ động.", enAvoid: "Avoid carrying every responsibility yourself solely to maintain control." },
    tianji: { viDo: "So sánh hai phương án cụ thể, chọn một rồi đặt mốc nhìn lại thay vì đổi liên tục.", enDo: "Compare two concrete options, choose one, and set a review point rather than switching plans continually.", viAvoid: "Tránh để sự linh hoạt biến thành thay đổi kế hoạch trước khi có phản hồi thật.", enAvoid: "Avoid letting flexibility turn into repeated changes before you have meaningful feedback." },
    taiyang: { viDo: "Chọn một đóng góp có ích cho người khác và thống nhất giới hạn thời gian của mình.", enDo: "Choose one useful contribution to others and agree on a realistic limit for the time you can give.", viAvoid: "Tránh nhận thêm việc hỗ trợ khi sức lực và trách nhiệm hiện tại chưa cho phép.", enAvoid: "Avoid taking on additional support work without checking your energy and existing commitments." },
    wuqu: { viDo: "Chuyển mục tiêu thành một bước thực thi và kiểm tra nguồn lực cần dùng.", enDo: "Turn a goal into one executable step and check the resources required to complete it.", viAvoid: "Tránh quyết định quá nhanh chỉ vì muốn thấy kết quả ngay.", enAvoid: "Avoid deciding too quickly solely because you want an immediate result." },
    tiantong: { viDo: "Tìm điểm hai bên có thể đồng thuận rồi nói rõ nhu cầu chưa được đáp ứng.", enDo: "Identify a point of agreement, then state a need that has not yet been addressed.", viAvoid: "Tránh giữ hòa khí bằng cách bỏ qua nhu cầu quan trọng của mình.", enAvoid: "Avoid preserving harmony by overlooking your own important needs." },
    lianzhen: { viDo: "Viết rõ nguyên tắc cần giữ và điều có thể thương lượng trong tình huống hiện tại.", enDo: "Write down the principle you need to preserve and what can be negotiated in the current situation.", viAvoid: "Tránh xem mọi khác biệt là sự vi phạm nguyên tắc.", enAvoid: "Avoid treating every difference as a violation of your principles." },
    tianfu: { viDo: "Kiểm kê điều đang có và chọn một cách giữ nguồn lực ổn định.", enDo: "Take stock of what you have and choose one practical way to maintain stable resources.", viAvoid: "Tránh giữ một cách làm chỉ vì nó quen thuộc khi nhu cầu đã thay đổi.", enAvoid: "Avoid preserving a familiar method after the need it served has changed." },
    taiyin: { viDo: "Dành thời gian lắng nghe rồi nói rõ điều mình hiểu để tránh đoán sai.", enDo: "Make time to listen, then state what you understood so the other person can correct a misunderstanding.", viAvoid: "Tránh giữ mọi suy nghĩ bên trong khi cần một cuộc trao đổi trực tiếp.", enAvoid: "Avoid keeping every concern inside when a direct conversation is needed." },
    tanlang: { viDo: "Chọn một trải nghiệm mới phù hợp và đặt giới hạn cho thời gian hoặc chi phí.", enDo: "Choose one relevant new experience and set a clear limit on the time or cost involved.", viAvoid: "Tránh theo quá nhiều hướng cùng lúc khiến việc quan trọng bị bỏ dở.", enAvoid: "Avoid pursuing so many possibilities that important commitments remain unfinished." },
    jumen: { viDo: "Kiểm tra một nhận định bằng dữ kiện và đặt câu hỏi ngắn, rõ trước khi phản biện.", enDo: "Check one claim against evidence and ask a clear question before offering a critique.", viAvoid: "Tránh kéo cuộc trao đổi thành tranh luận khi mục tiêu là hiểu và phối hợp.", enAvoid: "Avoid turning a conversation into an argument when the goal is understanding and cooperation." },
    tianxiang: { viDo: "Thống nhất tiêu chuẩn công bằng và cách bàn giao để sự hỗ trợ được nhận đúng.", enDo: "Agree on a fair standard and a clear handover so that support can be used effectively.", viAvoid: "Tránh nhận vai trò hòa giải mà chưa làm rõ trách nhiệm của các bên.", enAvoid: "Avoid taking a mediating role before clarifying each person's responsibility." },
    tianliang: { viDo: "Hỏi người được hỗ trợ cần gì trước khi góp lời khuyên hoặc nhận trách nhiệm bảo trợ.", enDo: "Ask what support someone needs before giving advice or taking a protective role.", viAvoid: "Tránh quyết định thay người khác chỉ vì muốn giúp họ.", enAvoid: "Avoid making another person's decision for them solely because you want to help." },
    qisha: { viDo: "Chọn một thử thách có phạm vi rõ, chuẩn bị phương án dự phòng rồi mới hành động.", enDo: "Choose a challenge with a clear scope and prepare a fallback before taking action.", viAvoid: "Tránh đồng nhất sự độc lập với việc phải tự xử lý mọi thử thách.", enAvoid: "Avoid equating independence with having to face every challenge alone." },
    pojun: { viDo: "Thử một thay đổi nhỏ có thể đánh giá trước khi thay toàn bộ cách làm.", enDo: "Test a small, assessable change before replacing the entire way you work.", viAvoid: "Tránh bỏ nền tảng đang hữu ích chỉ vì muốn làm mới mọi thứ.", enAvoid: "Avoid discarding a useful foundation solely for the sake of making everything new." },
};
function principal(palace: Palace) {
    return palace.stars.filter(star => star.category === "major" || (star.category === undefined && ziweiMajorStarMeaning("vi", star.id) !== null));
}
function sourcePalaces(chart: NormalizedZiweiChartV1, palace: Palace): Palace[] {
    if (principal(palace).length)
        return [palace];
    const relations = getPalaceRelations(palace.id, chart.palaces);
    return [relations.oppositeId, ...relations.trineIds].map(id => chart.palaces.find(p => p.id === id)).filter((p): p is Palace => Boolean(p));
}
function sourceMeanings(chart: NormalizedZiweiChartV1, palace: Palace, locale: Locale) {
    return sourcePalaces(chart, palace).flatMap(source => principal(source).map(star => ({ source, star, meaning: ziweiMajorStarMeaning(locale, star.id) }))).filter(item => item.meaning !== null);
}
function caveat(chart: NormalizedZiweiChartV1, locale: Locale) {
    return chart.provisional ? locale === "vi" ? "Giờ sinh chưa chắc chắn: vị trí cung và sao đang tạm tính, cần kiểm tra lại trước khi áp dụng nhận định." : "Birth time is uncertain: palace and star placements are provisional and should be checked before applying the interpretation." : "";
}
function facts(chart: NormalizedZiweiChartV1, palace: Palace, locale: Locale): string {
    const majors = principal(palace);
    const starText = majors.length ? majors.map(s => `${label(locale, s.id)} (${label(locale, s.brightness)})`).join(", ") : locale === "vi" ? "không có chính tinh tọa thủ (vô chính diệu)" : "no resident principal star (an empty principal-star palace)";
    const relations = getPalaceRelations(palace.id, chart.palaces);
    const opposite = relations.oppositeId ? label(locale, relations.oppositeId) : locale === "vi" ? "chưa xác định" : "unavailable";
    const trines = relations.trineIds.map(id => label(locale, id)).join(", ");
    return locale === "vi" ? `${label(locale, palace.id)} an tại ${label(locale, palace.earthlyBranchId)}; dữ liệu ghi nhận ${starText}. Cung đối là ${opposite}; hai cung tam hợp là ${trines}. Đây là quan hệ theo vị trí địa chi, không phải sao được thêm vào cung đang đọc.` : `${label(locale, palace.id)} is placed at ${label(locale, palace.earthlyBranchId)}; its recorded principal-star configuration is ${starText}. Its opposite palace is ${opposite}, and its two trine palaces are ${trines}. These relationships follow branch positions; they do not move the other palaces' stars into this palace.`;
}
function interpretation(chart: NormalizedZiweiChartV1, palace: Palace, locale: Locale): string {
    const sources = sourceMeanings(chart, palace, locale);
    const borrowed = !principal(palace).length;
    const intro = borrowed ? locale === "vi" ? "Cung vô chính diệu cần đọc cùng nguồn chiếu thực:" : "This empty principal-star palace is read alongside its actual related sources:" : locale === "vi" ? "Trong bộ sao tọa thủ:" : "Within the resident configuration:";
    const meanings = sources.slice(0, 4).map(item => locale === "vi" ? `${label(locale, item.star.id)} tại ${label(locale, item.source.id)} gợi ${item.meaning}` : `${label(locale, item.star.id)} in ${label(locale, item.source.id)} suggests ${item.meaning}`).join("; ");
    const unknown = sourcePalaces(chart, palace).flatMap(principal).filter(star => ziweiMajorStarMeaning(locale, star.id) === null).length;
    const limit = unknown ? locale === "vi" ? ` Có ${unknown} chính tinh chưa có ý nghĩa được đối chiếu; phần này không gán phẩm chất cho chúng.` : ` There are ${unknown} principal stars without verified meanings; no character traits are assigned to them.` : "";
    const ending = borrowed ? locale === "vi" ? "Đây là ảnh hưởng chiếu, không phải sao tọa thủ; công thức chỉ mượn nửa trọng số chính tinh cung đối. Không có chính tinh không đồng nghĩa thiếu năng lực." : "These are related-palace influences, not resident stars. The formula borrows half the principal-star weight from the opposite palace. An empty palace does not imply a lack of ability." : locale === "vi" ? "Những nét này có thể nâng đỡ cách xử lý tình huống khi được sử dụng có chủ đích; cần đối chiếu trải nghiệm thật thay vì xem chúng là tính cách cố định." : "These themes may support how you respond to a situation when used deliberately. Compare them with lived experience rather than treating them as fixed traits or a complete description of your personality.";
    return `${intro} ${meanings || (locale === "vi" ? "chưa có chính tinh với ý nghĩa được đối chiếu trong các cung nguồn." : "no verified principal-star meaning is available in the source palaces.")}. ${ending}${limit}`;
}
function scoreText(chart: NormalizedZiweiChartV1, palace: Palace, locale: Locale): string {
    const score = computeNormalizedPalaceScores(chart).get(palace.id)!;
    return locale === "vi" ? `Điểm cấu trúc là ${score.score}/100: nền ${score.parts.base}, phần riêng ${Number(score.parts.own.toFixed(2))}, phần chiếu ${Number(score.parts.chieu.toFixed(2))}. Con số cho biết mức hỗ trợ trong công thức sao đã công bố, không phải tỷ lệ thành công hay mức tốt xấu của đời người.` : `The structural score is ${score.score}/100: base ${score.parts.base}, own component ${Number(score.parts.own.toFixed(2))}, and related-palace contribution ${Number(score.parts.chieu.toFixed(2))}. This describes support within the published star-weight formula, not a success probability or a judgement about the quality of your life.`;
}
function actions(chart: NormalizedZiweiChartV1, palace: Palace, locale: Locale) {
    const sources = sourceMeanings(chart, palace, locale);
    const chosen = sources.find(item => practices[item.star.id.replace("ziwei.star.", "")]);
    const practice = chosen ? practices[chosen.star.id.replace("ziwei.star.", "")] : undefined;
    const domain = domains[palace.id.replace("ziwei.palace.", "")]!;
    const prefix = chosen ? (locale === "vi" ? `Từ nét của ${label(locale, chosen.star.id)}${chosen.source.id !== palace.id ? ` chiếu từ ${label(locale, chosen.source.id)}` : ""}: ` : `From the theme of ${label(locale, chosen.star.id)}${chosen.source.id !== palace.id ? ` in related ${label(locale, chosen.source.id)}` : ""}: `) : "";
    return { do: [domain[locale === "vi" ? "viDo" : "enDo"], practice ? prefix + practice[locale === "vi" ? "viDo" : "enDo"] : locale === "vi" ? "Kiểm tra vị trí sao và giới hạn dữ liệu trước khi tìm ý nghĩa cụ thể." : "Check the star placements and data limitations before seeking a more specific interpretation."], avoid: [domain[locale === "vi" ? "viAvoid" : "enAvoid"], practice ? prefix + practice[locale === "vi" ? "viAvoid" : "enAvoid"] : locale === "vi" ? "Tránh tự gán phẩm chất cho chính tinh chưa có ý nghĩa được đối chiếu." : "Avoid assigning traits to principal stars without verified meanings."] };
}
function balance(chart: NormalizedZiweiChartV1, palace: Palace, locale: Locale) {
    const score = computeNormalizedPalaceScores(chart).get(palace.id)!;
    const relation = getPalaceRelations(palace.id, chart.palaces);
    const own = Number(score.parts.own.toFixed(2)), related = Number(score.parts.chieu.toFixed(2));
    return locale === "vi" ? `Ở ${label(locale, palace.id)}, phần riêng đóng góp ${own} điểm và phần chiếu ${related} điểm. ${related > 0 ? "Các cung chiếu đang thêm trọng số hỗ trợ trong công thức" : related < 0 ? "Các cung chiếu đang giảm trọng số hỗ trợ trong công thức" : "Phần chiếu hiện cân bằng theo công thức"}; cần nhìn ${[relation.oppositeId, ...relation.trineIds].filter(Boolean).map(id => label(locale, id!)).join(", ")} cùng cấu trúc đang đọc. Một lựa chọn thực tế là ${actions(chart, palace, locale).do[1]!.replace(/^Từ nét của .*?: /u, "").replace(/^./u, c => c.toLocaleLowerCase("vi"))}` : `In ${label(locale, palace.id)}, the own component is ${own} points and the related-palace contribution is ${related} points. ${related > 0 ? "Related palaces add supporting weight in the formula" : related < 0 ? "Related palaces reduce supporting weight in the formula" : "Related-palace weight is balanced in the formula"}. Consider ${[relation.oppositeId, ...relation.trineIds].filter(Boolean).map(id => label(locale, id!)).join(", ")} alongside this configuration. A practical response is to ${actions(chart, palace, locale).do[1]!.replace(/^From the theme of .*?: /u, "").replace(/^./u, c => c.toLowerCase())}`;
}
export function compileFreeStructuralPalace(chart: NormalizedZiweiChartV1, palaceId: string, locale: Locale): FreeStructuralPalaceDocV1 {
    const palace = chart.palaces.find(p => p.id === palaceId);
    if (!palace)
        throw new Error("STRUCTURAL_PALACE_NOT_FOUND");
    const domain = domains[palaceId.replace("ziwei.palace.", "")]!;
    const sources = sourceMeanings(chart, palace, locale);
    const configuration = sources.slice(0, 2).map(item => `${label(locale, item.star.id)}${item.source.id !== palace.id ? (locale === "vi" ? " chiếu từ " : " in related ") + label(locale, item.source.id) : ""}: ${item.meaning}`).join("; ");
    const conclusion = `${domain[locale]} ${configuration || (locale === "vi" ? "Chưa có ý nghĩa chính tinh được đối chiếu để kết luận cụ thể." : "No verified principal-star meaning is available for a specific conclusion.")} ${caveat(chart, locale)}`.trim();
    const advice = actions(chart, palace, locale);
    return FreeStructuralPalaceDocV1Schema.parse({ version: 1, sourceKind: "structural", palaceId, locale, title: label(locale, palaceId), conclusion, keyPoints: [facts(chart, palace, locale), scoreText(chart, palace, locale)], paragraphs: [interpretation(chart, palace, locale), balance(chart, palace, locale), `${advice.do[0]} ${advice.avoid[0]} ${caveat(chart, locale)}`.trim()], do: advice.do, avoid: advice.avoid });
}
export function compileFreeStructuralOverview(chart: NormalizedZiweiChartV1, locale: Locale): FreeStructuralOverviewDocV1 {
    const section = (id: string, title: string, paragraphs: string[]) => ({ id, title, paragraphs });
    const life = chart.palaces.find(p => p.id === chart.soulPalaceId)!;
    const body = chart.palaces.find(p => p.id === chart.bodyPalaceId)!;
    const travel = chart.palaces.find(p => p.id === "ziwei.palace.travel");
    const bodyThemes = sourceMeanings(chart, body, locale).slice(0, 2).map(item => `${label(locale, item.star.id)}${item.source.id !== body.id ? (locale === "vi" ? " chiếu từ " : " in related ") + label(locale, item.source.id) : ""}: ${item.meaning}`).join("; ");
    const sections = [section("life", locale === "vi" ? "Nền tính cách từ cung Mệnh" : "Your starting point: the Life Palace", [facts(chart, life, locale), interpretation(chart, life, locale)]), section("body", locale === "vi" ? "Cung Thân và cách đi vào hành động" : "The Body Palace and practical expression", [locale === "vi" ? `Thân cư ${label(locale, body.id)}, an tại ${label(locale, body.earthlyBranchId)}. ${body.id === life.id ? "Mệnh và Thân cùng một cung: cùng bộ sao được nhìn từ hai góc tính cách và hành động, không cộng thành hai bộ sao độc lập." : `Mệnh ở ${label(locale, life.earthlyBranchId)} và Thân ở ${label(locale, body.earthlyBranchId)}: nền tính cách được đặt cạnh lĩnh vực thể hiện hành động, không dùng một cung thay thế cung còn lại.`} ${bodyThemes ? `Ở góc hành động, ${!principal(body).length ? "Thân cư cung vô chính diệu: các sao sau là nguồn chiếu, không tọa thủ. " : ""}${bodyThemes}.` : "Nguồn chính tinh chưa đủ để nêu nét hành động cụ thể."}` : `The Body Palace resides in ${label(locale, body.id)}, at ${label(locale, body.earthlyBranchId)}. ${body.id === life.id ? "Life and Body share a palace: the same configuration is considered through personality and action, not counted as two independent star sets." : `Life is placed at ${label(locale, life.earthlyBranchId)} and Body at ${label(locale, body.earthlyBranchId)}. Consider your starting approach alongside the domain where action is expressed; one palace does not replace the other.`} ${bodyThemes ? `For practical expression, ${!principal(body).length ? "the Body Palace has no resident principal stars; these are related influences, not resident stars. " : ""}the verified themes are ${bodyThemes}.` : "The principal-star sources are insufficient to describe a specific action theme."}`, balance(chart, body, locale)])];
    for (const key of ["career", "wealth", "spouse", "travel", "fortune", "parents"]) {
        const palace = chart.palaces.find(p => p.id === `ziwei.palace.${key}`);
        if (!palace)
            continue;
        const domain = domains[key]!, advice = actions(chart, palace, locale);
        sections.push(section(key, label(locale, palace.id), [`${domain[locale]} ${facts(chart, palace, locale)}`, `${interpretation(chart, palace, locale)} ${advice.do[1]} ${advice.avoid[0]}`]));
    }
    const scores = [...computeNormalizedPalaceScores(chart).values()].sort((a, b) => b.score - a.score || a.palaceId.localeCompare(b.palaceId));
    const high = scores[0]!, low = scores.at(-1)!;
    const highPalace = chart.palaces.find(p => p.id === high.palaceId)!, lowPalace = chart.palaces.find(p => p.id === low.palaceId)!;
    sections.push(section("synthesis", locale === "vi" ? "Điểm nâng đỡ và điều cần cân bằng" : "Support, tension, and a practical next step", [locale === "vi" ? `${label(locale, high.palaceId)} có điểm cao nhất (${high.score}/100), còn ${label(locale, low.palaceId)} thấp nhất (${low.score}/100). ${balance(chart, highPalace, locale)} Đối với ${label(locale, low.palaceId)}, ${actions(chart, lowPalace, locale).avoid[1]}` : `${label(locale, high.palaceId)} has the highest score (${high.score}/100), while ${label(locale, low.palaceId)} has the lowest (${low.score}/100). ${balance(chart, highPalace, locale)} For ${label(locale, low.palaceId)}, ${actions(chart, lowPalace, locale).avoid[1]}`, locale === "vi" ? `Mệnh đặt nền tại ${label(locale, life.earthlyBranchId)}, Thân đi vào ${label(locale, body.id)}${travel ? `, còn Thiên Di tại ${label(locale, travel.earthlyBranchId)} là góc nhìn về môi trường bên ngoài` : ""}. Hãy đối chiếu điều mình định làm, cách mình thực hiện và phản hồi thực tế của người khác; ba góc này không buộc phải trùng nhau. ${caveat(chart, locale) || "Tổng quan này chỉ đọc cấu trúc bản sinh, không phải dự báo ngày hoặc năm."} ${chart.warnings?.length ? "Dữ liệu có cảnh báo tính toán; hãy kiểm tra dữ kiện trước khi đi sâu." : "Bạn có thể đối chiếu tên sao và vị trí trực tiếp trên lá số."}` : `Life starts at ${label(locale, life.earthlyBranchId)}, Body is expressed through ${label(locale, body.id)}${travel ? `, and Travel at ${label(locale, travel.earthlyBranchId)} offers the perspective of the outside environment` : ""}. Compare what you intended, how you acted, and the feedback you received; these three perspectives need not be identical. ${caveat(chart, locale) || "This overview reads natal structure, not daily or annual predictions."} ${chart.warnings?.length ? "The calculation has warnings; check the evidence before drawing further conclusions." : "You can compare star names and placements directly with the chart."}`]));
    return FreeStructuralOverviewDocV1Schema.parse({ version: 1, sourceKind: "structural", locale, sections });
}
