INSERT INTO "ai_model_pricing" (
  "pricing_version",
  "provider_id",
  "model_id",
  "currency",
  "input_price_per_million",
  "output_price_per_million",
  "cached_input_price_per_million",
  "effective_from",
  "source",
  "source_currency",
  "source_reference",
  "fx_source",
  "fx_rate",
  "fx_timestamp",
  "reference_metadata",
  "status"
) VALUES (
  'openrouter-deepseek-flash-v1-20260920',
  'openrouter',
  '~deepseek/deepseek-flash-latest',
  'VND',
  3394,
  13577,
  68,
  '2026-09-20T00:00:00Z',
  'OpenRouter models API',
  'USD',
  'https://openrouter.ai/api/v1/models',
  'Vietcombank USD sell',
  26110,
  '2026-09-20T00:00:00Z',
  '{"requested_model_id":"~deepseek/deepseek-flash-latest","resolved_model_id":"deepseek/deepseek-v4.1-flash"}'::jsonb,
  'active'
);
